# Generated by Django 4.2.3 on 2023-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0003_alter_foods_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
