# Generated by Django 4.2.3 on 2023-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0004_foods_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='foods/'),
        ),
    ]
