# Generated by Django 4.2.3 on 2023-07-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0005_alter_foods_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='photo',
        ),
    ]
