# Generated by Django 4.2.3 on 2023-07-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0006_remove_foods_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='photo',
            field=models.ImageField(null=True, upload_to='Foods/'),
        ),
    ]
