# Generated by Django 4.2.3 on 2023-07-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0007_foods_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='food_type',
            field=models.CharField(choices=[('D', 'نوشیدنی'), ('B', 'صبحانه'), ('DI', 'شام'), ('L', 'ناهار')], max_length=10, null=True, verbose_name='نوع غذا'),
        ),
    ]
