# Generated by Django 4.2.3 on 2023-07-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0008_foods_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='food_type',
            field=models.CharField(choices=[('Drink', 'نوشیدنی'), ('BreakFast', 'صبحانه'), ('Dinner', 'شام'), ('Lunch', 'ناهار')], max_length=10, null=True, verbose_name='نوع غذا'),
        ),
    ]
