# Generated by Django 4.2.3 on 2023-07-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(max_length=50, verbose_name='ساعت'),
        ),
    ]
